#region Copyright notice and license

// Copyright 2025 The gRPC Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#endregion

using System.Buffers.Binary;
using System.Diagnostics;
using System.Text;
using NUnit.Framework;

namespace Grpc.Net.SharedMemory.Tests;

/// <summary>
/// Tests verifying byte-level compatibility with grpc-go-shmem.
/// These tests can be used to generate binary dumps for cross-language verification.
/// </summary>
[TestFixture]
public class InteropTests
{
    private static readonly string GoInteropDir = Path.Combine(
        AppDomain.CurrentDomain.BaseDirectory, "..", "..", "..", "GoInterop");

    private static string GoVerifierPath => Path.Combine(GoInteropDir, 
        OperatingSystem.IsWindows() ? "segment_verify.exe" : "segment_verify");

    private static string GoVerifierBuildCommand => OperatingSystem.IsWindows()
        ? "go build -o segment_verify.exe segment_verify.go"
        : "go build -o segment_verify segment_verify.go";

    /// <summary>
    /// Verifies .NET can correctly read a segment header generated by Go.
    /// </summary>
    [Test]
    public void GoBinaryCompatibility_SegmentHeader_CanBeRead()
    {
        var goSegmentPath = Path.Combine(GoInteropDir, "go_segment_header.bin");
        if (!File.Exists(goSegmentPath))
        {
            Assert.Ignore($"Go binary dump not found at {goSegmentPath}. Run: cd GoInterop && go run binary_dump.go -output .");
        }

        var bytes = File.ReadAllBytes(goSegmentPath);
        Assert.That(bytes.Length, Is.EqualTo(128), "Segment header should be 128 bytes");

        // Parse header using our structs
        var header = new SegmentHeader();
        var handle = System.Runtime.InteropServices.GCHandle.Alloc(bytes, System.Runtime.InteropServices.GCHandleType.Pinned);
        try
        {
            header = System.Runtime.InteropServices.Marshal.PtrToStructure<SegmentHeader>(handle.AddrOfPinnedObject());
        }
        finally
        {
            handle.Free();
        }

        // Verify magic
        var expectedMagic = BitConverter.ToUInt64(ShmConstants.SegmentMagicBytes);
        Assert.That(header.MagicValue, Is.EqualTo(expectedMagic), "Magic should be GRPCSHM\\0");
        Assert.That(header.Version, Is.EqualTo(1u), "Version");
        Assert.That(header.TotalSize, Is.EqualTo(0x20000UL), "TotalSize");
        Assert.That(header.RingAOffset, Is.EqualTo(0x80UL), "RingAOffset");
        Assert.That(header.RingACapacity, Is.EqualTo(0x10000UL), "RingACapacity");
        Assert.That(header.ServerPID, Is.EqualTo(1234u), "ServerPID");
        Assert.That(header.ClientPID, Is.EqualTo(5678u), "ClientPID");
        Assert.That(header.ServerReady, Is.EqualTo(1u), "ServerReady");
        Assert.That(header.MaxStreams, Is.EqualTo(100u), "MaxStreams");
    }

    /// <summary>
    /// Verifies .NET can correctly read a ring header generated by Go.
    /// </summary>
    [Test]
    public void GoBinaryCompatibility_RingHeader_CanBeRead()
    {
        var goRingPath = Path.Combine(GoInteropDir, "go_ring_header.bin");
        if (!File.Exists(goRingPath))
        {
            Assert.Ignore($"Go binary dump not found at {goRingPath}. Run: cd GoInterop && go run binary_dump.go -output .");
        }

        var bytes = File.ReadAllBytes(goRingPath);
        Assert.That(bytes.Length, Is.EqualTo(64), "Ring header should be 64 bytes");

        // Parse header using our structs
        var header = new RingHeader();
        var handle = System.Runtime.InteropServices.GCHandle.Alloc(bytes, System.Runtime.InteropServices.GCHandleType.Pinned);
        try
        {
            header = System.Runtime.InteropServices.Marshal.PtrToStructure<RingHeader>(handle.AddrOfPinnedObject());
        }
        finally
        {
            handle.Free();
        }

        Assert.That(header.Capacity, Is.EqualTo(4096UL), "Capacity");
        Assert.That(header.WriteIdx, Is.EqualTo(100UL), "WriteIdx");
        Assert.That(header.ReadIdx, Is.EqualTo(50UL), "ReadIdx");
        Assert.That(header.DataSeq, Is.EqualTo(10u), "DataSeq");
        Assert.That(header.SpaceSeq, Is.EqualTo(5u), "SpaceSeq");
        Assert.That(header.Closed, Is.EqualTo(0u), "Closed");
        Assert.That(header.ContigSeq, Is.EqualTo(7u), "ContigSeq");
    }

    /// <summary>
    /// Verifies .NET can correctly read a frame header generated by Go.
    /// </summary>
    [Test]
    public void GoBinaryCompatibility_FrameHeader_CanBeRead()
    {
        var goFramePath = Path.Combine(GoInteropDir, "go_frame_header.bin");
        if (!File.Exists(goFramePath))
        {
            Assert.Ignore($"Go binary dump not found at {goFramePath}. Run: cd GoInterop && go run binary_dump.go -output .");
        }

        var bytes = File.ReadAllBytes(goFramePath);
        Assert.That(bytes.Length, Is.EqualTo(16), "Frame header should be 16 bytes");

        // Decode using our FrameHeader
        var header = FrameHeader.DecodeFrom(bytes);
        Assert.That(header.Length, Is.EqualTo(100u), "Length");
        Assert.That(header.StreamId, Is.EqualTo(1u), "StreamId");
        Assert.That(header.Type, Is.EqualTo(FrameType.Headers), "Type");
        Assert.That(header.Flags, Is.EqualTo(HeadersFlags.Initial), "Flags");
    }
    /// <summary>
    /// Verifies frame header encoding matches grpc-go-shmem format.
    ///
    /// Go struct (16 bytes little-endian):
    /// type FrameHeader struct {
    ///     Length    uint32  // offset 0
    ///     StreamID  uint32  // offset 4
    ///     Type      uint8   // offset 8
    ///     Flags     uint8   // offset 9
    ///     Reserved1 uint16  // offset 10
    ///     Reserved2 uint32  // offset 12
    /// }
    /// </summary>
    [Test]
    public void FrameHeader_ByteLayout_MatchesGo()
    {
        var header = new FrameHeader
        {
            Length = 0x12345678,
            StreamId = 0xABCDEF01,
            Type = FrameType.Message,
            Flags = 0x42
        };

        var bytes = new byte[16];
        header.EncodeTo(bytes);

        // Verify little-endian layout
        Assert.That(BinaryPrimitives.ReadUInt32LittleEndian(bytes.AsSpan(0, 4)), Is.EqualTo(0x12345678), "Length at offset 0");
        Assert.That(BinaryPrimitives.ReadUInt32LittleEndian(bytes.AsSpan(4, 4)), Is.EqualTo(0xABCDEF01), "StreamID at offset 4");
        Assert.That(bytes[8], Is.EqualTo((byte)FrameType.Message), "Type at offset 8");
        Assert.That(bytes[9], Is.EqualTo(0x42), "Flags at offset 9");
        Assert.That(bytes[10], Is.EqualTo(0), "Reserved1 at offset 10");
        Assert.That(bytes[11], Is.EqualTo(0), "Reserved1 at offset 11");
        Assert.That(BinaryPrimitives.ReadUInt32LittleEndian(bytes.AsSpan(12, 4)), Is.EqualTo(0), "Reserved2 at offset 12");
    }

    /// <summary>
    /// Verifies ring header layout matches grpc-go-shmem format.
    /// </summary>
    [Test]
    public void RingHeader_ByteLayout_MatchesGo()
    {
        // Verify struct offsets match grpc-go-shmem ring.go RingHeader
        Assert.That(System.Runtime.InteropServices.Marshal.OffsetOf<RingHeader>(nameof(RingHeader.Capacity)), Is.EqualTo((IntPtr)0x00));
        Assert.That(System.Runtime.InteropServices.Marshal.OffsetOf<RingHeader>(nameof(RingHeader.WriteIdx)), Is.EqualTo((IntPtr)0x08));
        Assert.That(System.Runtime.InteropServices.Marshal.OffsetOf<RingHeader>(nameof(RingHeader.ReadIdx)), Is.EqualTo((IntPtr)0x10));
        Assert.That(System.Runtime.InteropServices.Marshal.OffsetOf<RingHeader>(nameof(RingHeader.DataSeq)), Is.EqualTo((IntPtr)0x18));
        Assert.That(System.Runtime.InteropServices.Marshal.OffsetOf<RingHeader>(nameof(RingHeader.SpaceSeq)), Is.EqualTo((IntPtr)0x1C));
        Assert.That(System.Runtime.InteropServices.Marshal.OffsetOf<RingHeader>(nameof(RingHeader.Closed)), Is.EqualTo((IntPtr)0x20));
        Assert.That(System.Runtime.InteropServices.Marshal.OffsetOf<RingHeader>(nameof(RingHeader.Pad)), Is.EqualTo((IntPtr)0x24));
        Assert.That(System.Runtime.InteropServices.Marshal.OffsetOf<RingHeader>(nameof(RingHeader.ContigSeq)), Is.EqualTo((IntPtr)0x28));
        Assert.That(System.Runtime.InteropServices.Marshal.OffsetOf<RingHeader>(nameof(RingHeader.SpaceWaiters)), Is.EqualTo((IntPtr)0x2C));
        Assert.That(System.Runtime.InteropServices.Marshal.OffsetOf<RingHeader>(nameof(RingHeader.ContigWaiters)), Is.EqualTo((IntPtr)0x30));
        Assert.That(System.Runtime.InteropServices.Marshal.OffsetOf<RingHeader>(nameof(RingHeader.DataWaiters)), Is.EqualTo((IntPtr)0x34));
    }

    /// <summary>
    /// Verifies segment header layout matches grpc-go-shmem format.
    /// </summary>
    [Test]
    public void SegmentHeader_ByteLayout_MatchesGo()
    {
        // Verify struct offsets match grpc-go-shmem shm_segment.go SegmentHeader
        Assert.That(System.Runtime.InteropServices.Marshal.OffsetOf<SegmentHeader>(nameof(SegmentHeader.MagicValue)), Is.EqualTo((IntPtr)0x00));
        Assert.That(System.Runtime.InteropServices.Marshal.OffsetOf<SegmentHeader>(nameof(SegmentHeader.Version)), Is.EqualTo((IntPtr)0x08));
        Assert.That(System.Runtime.InteropServices.Marshal.OffsetOf<SegmentHeader>(nameof(SegmentHeader.Flags)), Is.EqualTo((IntPtr)0x0C));
        Assert.That(System.Runtime.InteropServices.Marshal.OffsetOf<SegmentHeader>(nameof(SegmentHeader.TotalSize)), Is.EqualTo((IntPtr)0x10));
        Assert.That(System.Runtime.InteropServices.Marshal.OffsetOf<SegmentHeader>(nameof(SegmentHeader.RingAOffset)), Is.EqualTo((IntPtr)0x18));
        Assert.That(System.Runtime.InteropServices.Marshal.OffsetOf<SegmentHeader>(nameof(SegmentHeader.RingACapacity)), Is.EqualTo((IntPtr)0x20));
        Assert.That(System.Runtime.InteropServices.Marshal.OffsetOf<SegmentHeader>(nameof(SegmentHeader.RingBOffset)), Is.EqualTo((IntPtr)0x28));
        Assert.That(System.Runtime.InteropServices.Marshal.OffsetOf<SegmentHeader>(nameof(SegmentHeader.RingBCapacity)), Is.EqualTo((IntPtr)0x30));
        Assert.That(System.Runtime.InteropServices.Marshal.OffsetOf<SegmentHeader>(nameof(SegmentHeader.ServerPID)), Is.EqualTo((IntPtr)0x38));
        Assert.That(System.Runtime.InteropServices.Marshal.OffsetOf<SegmentHeader>(nameof(SegmentHeader.ClientPID)), Is.EqualTo((IntPtr)0x3C));
        Assert.That(System.Runtime.InteropServices.Marshal.OffsetOf<SegmentHeader>(nameof(SegmentHeader.ServerReady)), Is.EqualTo((IntPtr)0x40));
        Assert.That(System.Runtime.InteropServices.Marshal.OffsetOf<SegmentHeader>(nameof(SegmentHeader.ClientReady)), Is.EqualTo((IntPtr)0x44));
        Assert.That(System.Runtime.InteropServices.Marshal.OffsetOf<SegmentHeader>(nameof(SegmentHeader.Closed)), Is.EqualTo((IntPtr)0x48));
        Assert.That(System.Runtime.InteropServices.Marshal.OffsetOf<SegmentHeader>(nameof(SegmentHeader.Pad)), Is.EqualTo((IntPtr)0x4C));
        Assert.That(System.Runtime.InteropServices.Marshal.OffsetOf<SegmentHeader>(nameof(SegmentHeader.MaxStreams)), Is.EqualTo((IntPtr)0x50));
    }

    /// <summary>
    /// Verifies magic string format matches "GRPCSHM\0".
    /// </summary>
    [Test]
    public void SegmentMagic_MatchesGoFormat()
    {
        var magicBytes = ShmConstants.SegmentMagicBytes.ToArray();

        Assert.That(magicBytes.Length, Is.EqualTo(8));
        Assert.That(Encoding.ASCII.GetString(magicBytes), Is.EqualTo("GRPCSHM\0"));
    }

    /// <summary>
    /// Verifies HeadersV1 encoding format matches grpc-go-shmem.
    /// </summary>
    [Test]
    public void HeadersV1_Encoding_MatchesGo()
    {
        var headers = new HeadersV1
        {
            Version = 1,
            HeaderType = 0, // Client headers
            Method = "/test.Service/Method",
            Authority = "localhost",
            DeadlineUnixNano = 0,
            Metadata = new[] { new MetadataKV("custom-key", "value1") }
        };

        var encoded = headers.Encode();

        // Verify format
        Assert.That(encoded[0], Is.EqualTo(1), "Version byte");
        Assert.That(encoded[1], Is.EqualTo(0), "HeaderType byte (client)");

        // Method length at offset 2 (4 bytes little-endian)
        var methodLen = BinaryPrimitives.ReadUInt32LittleEndian(encoded.AsSpan(2, 4));
        Assert.That(methodLen, Is.EqualTo((uint)headers.Method.Length));

        // Method string starts at offset 6
        var methodBytes = Encoding.UTF8.GetString(encoded.AsSpan(6, (int)methodLen));
        Assert.That(methodBytes, Is.EqualTo("/test.Service/Method"));
    }

    /// <summary>
    /// Verifies TrailersV1 encoding format matches grpc-go-shmem.
    /// </summary>
    [Test]
    public void TrailersV1_Encoding_MatchesGo()
    {
        var trailers = new TrailersV1
        {
            Version = 1,
            GrpcStatusCode = Grpc.Core.StatusCode.OK,
            GrpcStatusMessage = "Success",
            Metadata = Array.Empty<MetadataKV>()
        };

        var encoded = trailers.Encode();

        // Verify format
        Assert.That(encoded[0], Is.EqualTo(1), "Version byte");

        // Status code at offset 1 (4 bytes little-endian)
        var statusCode = BinaryPrimitives.ReadInt32LittleEndian(encoded.AsSpan(1, 4));
        Assert.That(statusCode, Is.EqualTo(0), "OK status code");

        // Message length at offset 5 (4 bytes little-endian)
        var msgLen = BinaryPrimitives.ReadUInt32LittleEndian(encoded.AsSpan(5, 4));
        Assert.That(msgLen, Is.EqualTo((uint)"Success".Length));
    }

    /// <summary>
    /// Generates a binary dump file for Go verification.
    /// </summary>
    [Test]
    [Explicit("Run manually to generate binary dump for Go verification")]
    public void GenerateBinaryDumpForGoVerification()
    {
        var dumpPath = Path.Combine(Path.GetTempPath(), "grpc_shm_binary_dump");
        Directory.CreateDirectory(dumpPath);

        // Dump frame header
        var frameHeader = new FrameHeader
        {
            Length = 100,
            StreamId = 1,
            Type = FrameType.Headers,
            Flags = HeadersFlags.Initial
        };
        var frameBytes = new byte[16];
        frameHeader.EncodeTo(frameBytes);
        File.WriteAllBytes(Path.Combine(dumpPath, "frame_header.bin"), frameBytes);

        // Dump ring header
        var ringHeader = new RingHeader
        {
            Capacity = 4096,
            WriteIdx = 0,
            ReadIdx = 0
        };
        var ringBytes = new byte[64];
        var handle = System.Runtime.InteropServices.GCHandle.Alloc(ringBytes, System.Runtime.InteropServices.GCHandleType.Pinned);
        try
        {
            System.Runtime.InteropServices.Marshal.StructureToPtr(ringHeader, handle.AddrOfPinnedObject(), false);
        }
        finally
        {
            handle.Free();
        }
        File.WriteAllBytes(Path.Combine(dumpPath, "ring_header.bin"), ringBytes);

        // Dump headers
        var headers = new HeadersV1
        {
            Version = 1,
            HeaderType = 0,
            Method = "/greet.Greeter/SayHello",
            Authority = "localhost",
            DeadlineUnixNano = 0,
            Metadata = Array.Empty<MetadataKV>()
        };
        File.WriteAllBytes(Path.Combine(dumpPath, "headers_v1.bin"), headers.Encode());

        // Dump trailers
        var trailers = new TrailersV1
        {
            Version = 1,
            GrpcStatusCode = Grpc.Core.StatusCode.OK,
            GrpcStatusMessage = "",
            Metadata = Array.Empty<MetadataKV>()
        };
        File.WriteAllBytes(Path.Combine(dumpPath, "trailers_v1.bin"), trailers.Encode());

        Console.WriteLine($"Binary dumps written to: {dumpPath}");
        Assert.Pass($"Binary dumps generated at {dumpPath}");
    }

    /// <summary>
    /// Cross-language test: Creates a segment in .NET, verifies Go can read it.
    /// </summary>
    [Test]
    public void CrossLanguage_GoCanReadDotNetSegment()
    {
        if (!File.Exists(GoVerifierPath))
        {
            Assert.Ignore($"Go verifier not found at {GoVerifierPath}. Build with: cd GoInterop && {GoVerifierBuildCommand}");
        }

        var segmentName = $"dotnet_test_{Guid.NewGuid():N}";
        using var segment = Segment.Create(segmentName, 4096, 100);

        try
        {
            // Run Go verifier
            var psi = new ProcessStartInfo
            {
                FileName = GoVerifierPath,
                Arguments = $"-name {segmentName}",
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                UseShellExecute = false,
                CreateNoWindow = true
            };

            using var process = Process.Start(psi);
            var output = process!.StandardOutput.ReadToEnd();
            var error = process.StandardError.ReadToEnd();
            process.WaitForExit(5000);

            Console.WriteLine($"Go output:\n{output}");
            if (!string.IsNullOrEmpty(error))
            {
                Console.WriteLine($"Go stderr:\n{error}");
            }

            Assert.That(process.ExitCode, Is.EqualTo(0), $"Go verifier failed with code {process.ExitCode}");
            Assert.That(output, Does.Contain("VERIFY_SUCCESS"), "Go should verify segment successfully");
            Assert.That(output, Does.Contain("Magic: \"GRPCSHM\\x00\""), "Magic should match");
            Assert.That(output, Does.Contain("Version: 1"), "Version should be 1");
            Assert.That(output, Does.Contain("RingA: offset=128, capacity=4096"), "RingA layout should match");
        }
        finally
        {
            // Cleanup is handled by Dispose, but we need to ensure the segment is disposed
            // before checking the file is deleted
        }
    }

    /// <summary>
    /// Cross-language test: Go creates segment, .NET reads it.
    /// </summary>
    [Test]
    public void CrossLanguage_DotNetCanReadGoSegment()
    {
        if (!File.Exists(GoVerifierPath))
        {
            Assert.Ignore($"Go verifier not found at {GoVerifierPath}. Build with: cd GoInterop && {GoVerifierBuildCommand}");
        }

        var segmentName = $"go_test_{Guid.NewGuid():N}";
        var segmentPath = OperatingSystem.IsLinux()
            ? Path.Combine("/dev/shm", $"grpc_shm_{segmentName}")
            : Path.Combine(Path.GetTempPath(), $"grpc_shm_{segmentName}");

        try
        {
            // Have Go create the segment
            var psi = new ProcessStartInfo
            {
                FileName = GoVerifierPath,
                Arguments = $"-name {segmentName} -create -capacity 4096",
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                UseShellExecute = false,
                CreateNoWindow = true
            };

            using var process = Process.Start(psi);
            process!.WaitForExit(5000);
            var output = process.StandardOutput.ReadToEnd();
            var error = process.StandardError.ReadToEnd();

            Assert.That(process.ExitCode, Is.EqualTo(0), $"Go create failed: {error}");
            Console.WriteLine($"Go created segment: {output}");

            // Now open with .NET
            using var segment = Segment.Open(segmentName);

            Assert.That(segment.Header.MagicValue, Is.EqualTo(BitConverter.ToUInt64(ShmConstants.SegmentMagicBytes)), "Magic");
            Assert.That(segment.Header.Version, Is.EqualTo(1u), "Version");
            Assert.That(segment.Header.RingACapacity, Is.EqualTo(4096UL), "RingA capacity");
            Assert.That(segment.Header.RingBCapacity, Is.EqualTo(4096UL), "RingB capacity");
            Assert.That(segment.Header.ServerReady, Is.EqualTo(1u), "ServerReady");
            Assert.That(segment.Header.MaxStreams, Is.EqualTo(100u), "MaxStreams");
        }
        finally
        {
            // Clean up Go-created segment
            try { File.Delete(segmentPath); } catch { }
        }
    }
}
